name: cellpose_v3
channels:
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - pandas
  - numpy
  - imageio
  - cellpose=3.1.1.3
  - tifffile
  - ipython
  - scikit-image
  - pytorch

